### ISSUE TITLE
Backend test is failing.

### ISSUE THREAD

**Issue by LemonPepperSeasoning** [SE701Team2/Updog#63]
**Describe the bug**
Test case "test/posts.test.js" is failing. 
Test Suites: 1 failed, 1 total
Tests:       2 failed, 11 passed, 13 total

**To Reproduce**
1. Go into backend folder and run "npm test test/posts.test.js"
2. See error

**Expected behavior**
Should pass all test.
(to be specific, should return the correct response code)

**Screenshots**
![Screen Shot 2022-03-12 at 2 35 57 AM](https://user-images.githubusercontent.com/60628111/157878195-8ee548f7-1903-4036-839a-22a07684a01f.jpg)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser : terminal/command line

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Dj5822** [comment]
I'm not getting the same error so I have no idea if this will help but,
try:
const decodedUser = await Authentication.extractUser(authToken)
instead of:
const decodedUser = Authentication.extractUser(authToken)
inside the post.js file for the put and delete methods.

I think the error you're getting right now is because you are failing to get the proper author in those two tests.

If that doesn't help try changing "else if (post.author === decodedUser.id)" such that both variables are casted into the same type. So basically, "else if (parseInt(post.author) === parseInt(decodedUser.id))"

**Comment by LemonPepperSeasoning** [comment]
This was due to me not correctly following the README instructions. 
The migration of database 'sequelize db:migrate --url "mysql://updogDev:password@localhost:3306/updog"' fixed the problem for me.
